# Generated by Django 3.2.6 on 2021-08-11 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employer',
            old_name='Location',
            new_name='location',
        ),
        migrations.AddField(
            model_name='employer',
            name='DatePublished',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='employer',
            name='deadline',
            field=models.DateTimeField(null=True),
        ),
    ]
