# Generated by Django 3.2.6 on 2021-08-11 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0002_auto_20210811_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='JobType',
            field=models.CharField(choices=[('Permanent', 'Permanent'), ('Contract', 'Contract')], max_length=200, null=True),
        ),
    ]
