# Generated by Django 3.2.6 on 2021-08-12 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0007_alter_employee_employer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='bsc',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employer',
            field=models.ManyToManyField(blank=True, to='vacancy.Employer'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='msc',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='employee',
            name='od',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phd',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
