# Generated by Django 3.2.6 on 2021-08-12 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0008_auto_20210812_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employer',
            field=models.ManyToManyField(blank=True, to='vacancy.Employer'),
        ),
    ]
