# Generated by Django 2.2 on 2021-08-12 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0009_alter_employee_employer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employer',
            field=models.ManyToManyField(blank=True, to='vacancy.Employer'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='employer',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
