# Generated by Django 3.2.6 on 2021-08-30 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0015_alter_employee_employer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employer',
            field=models.ManyToManyField(blank=True, to='vacancy.Employer'),
        ),
    ]
